name: yext_hol_transforms
version: '1.0.0'
config-version: 2

profile: yext_hol

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

seeds:
  yext_hol_transforms:
    +schema: ANALYTICS

models:
  yext_hol_transforms:
    staging:
      +materialized: view
      +tags: ['staging']
    intermediate:
      +materialized: view
      +tags: ['intermediate']
    marts:
      +materialized: table
      +tags: ['marts']
