name: yext_hol_transforms
version: '1.0.0'
config-version: 2

profile: yext_hol

model-paths: ["models"]

models:
  yext_hol_transforms:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
